# hosts/thinkpad-x1/hardware-configuration.nix
# This file is a placeholder.
# Generate the real one on the target machine with:
#   sudo nixos-generate-config --show-hardware-config > hosts/thinkpad-x1/hardware-configuration.nix
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];

  # Placeholder — replace with actual hardware-configuration.nix content
  # generated by nixos-generate-config on the target machine.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [];

  swapDevices = [];
  nixpkgs.hostPlatform = "x86_64-linux";
}
